development:
  dialect: postgres
  datasource: host=localhost dbname=travel-lists user=postgres sslmode=disable
  dir: migrations
  table: migrations

# production:
#   dialect: postgres
#   datasource: host=prodhost dbname=travel-lists user=${DB_USER} password=${DB_PASSWORD} sslmode=require
#   dir: migrations
#   table: migrations
