name: travel-lists

services:
  database:
    image: postgres:16.3
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=travel-lists
    volumes:
      - postgres:/var/lib/postgresql/data postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
